export const booksData = [
    {  // only non-fiction section here
        bookGenre: ["self-help", "psychology", "personal development"],
        isNonFiction: true,
        image: "./bookCovers/atomicHabits.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "productivity", "psychology"],
        isNonFiction: true,
        image: "./bookCovers/deepWork.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "productivity", "personal development"],
        isNonFiction: true,
        image: "./bookCovers/feelGoodProductivity.jpg",     
        alt: "current books cover",
    },
    {
        bookGenre: ["business", "psychology", "technology"],
        isNonFiction: true,
        image: "./bookCovers/hooked.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "personal development", "inspirational"],
        isNonFiction: true,
        image: "./bookCovers/howToGrowThroughWhatYouGo.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "personal development", "psychology"],
        isNonFiction: true,
        image: "./bookCovers/mastery.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "psychology", "communication"],
        isNonFiction: true,
        image: "./bookCovers/readPeoplelikeAbook.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "psychology", "personal development"],
        isNonFiction: true,
        image: "./bookCovers/subtelArtNotGiveFuck.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["philosophy", "critical thinking"],
        isNonFiction: true,
        image: "./bookCovers/theArtofLogic.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["psychology", "true-crime"],
        isNonFiction: true,
        image: "./bookCovers/theConfidenceGame.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "business", "personal development"],
        isNonFiction: true,
        image: "./bookCovers/theJoyofWork.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["self-help", "personal development", "masculinity"],
        isNonFiction: true,
        image: "./bookCovers/toBeAMan.jpg",
        alt: "current books cover",
    }, 
    {
        bookGenre: ["self-help", "philosophy", "masculinity", "psychology"],
        isNonFiction: true,
        image: "./bookCovers/theWayoftheSuperiorMan.webp",
        alt: "current books cover",
    }, 
    {       //now only fiction section here
        bookGenre: ["dystopian", "political fiction"],
        isNonFiction: false,
        image: "./bookCovers/1984.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "children's literature"],
        isNonFiction: false,
        image: "./bookCovers/aliceInWonderland.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["dystopian", "political fiction", "satire"],
        isNonFiction: false,
        image: "./bookCovers/animalFarm.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "comedy"],
        isNonFiction: false,
        image: "./bookCovers/cantervilleGhost.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "horror", "children's literature"],
        isNonFiction: false,
        image: "./bookCovers/Coraline.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["science fiction", "adventure", "fantasy"],
        isNonFiction: false,
        image: "./bookCovers/dune.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "young adult", "adventure"],
        isNonFiction: false,
        image: "./bookCovers/gobletOfFire.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["literary fiction", "drama", "coming-of-age"],
        isNonFiction: false,
        image: "./bookCovers/littleGirls.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["adventure", "literary fiction", "classic"],
        isNonFiction: false,
        image: "./bookCovers/mobyDick.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["historical fiction", "mystery", "drama"],
        isNonFiction: false,
        image: "./bookCovers/nothingForgotten.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["adventure", "fantasy", "manga", "animated series"],
        isNonFiction: false,
        image: "./bookCovers/onePiece.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "adventure", "animated series"],
        isNonFiction: false,
        image: "./bookCovers/overTheGardenWall.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["contemporary fiction", "young adult", "drama"],
        isNonFiction: false,
        image: "./bookCovers/stuckOnaSunday.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "adventure"],
        isNonFiction: false,
        image: "./bookCovers/theAlchemist.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["historical fiction", "drama", "war fiction"],
        isNonFiction: false,
        image: "./bookCovers/theBoyintheStrippedPajamas.jpg",
        alt: "current books cover",
    },
    {
        bookGenre: ["fantasy", "adventure"],
        isNonFiction: false,
        image: "./bookCovers/theHobbit.jpg",
        alt: "current books cover",
    },
]


export const quotesForHeader = [
    "To Be or Not to Be?",
"Hello, World!",
"Life is a Game!",
"I Love You 3000",
"Qaiser Means King",
"Reading Helped Me!",
"Breathe Books. Live Books. Love Books.",
"There are years that ask questions and years that answer.",
"The world breaks everyone, and afterward, some are strong at the broken places.",
"A journey of a thousand miles begins with a single step.",
"Imagination is more important than knowledge.",
"To love and be loved is to feel the sun from both sides.",
"Don’t count the days; make the days count.",
"Some books leave us free, and some books make us free.",
"Sometimes, even to live is an act of courage.",
"We are all broken, that's how the light gets in.",
"Every saint has a past, and every sinner has a future.",
"You don’t have to be perfect to be amazing.",
"A person who never made a mistake never tried anything new.",
"The only way to do great work is to love what you do.",
"A room without books is like a body without a soul.",
"There is no greater agony than bearing an untold story inside you.",
"Do not go where the path may lead, go instead where there is no path and leave a trail.",
"What we think, we become.",
"Sometimes you have to lose yourself to find yourself.",
"Believe you can and you're halfway there.",
"If you want to go fast, go alone. If you want to go far, go together.",
"The things we love tell us who we are.",
"Pain is inevitable; suffering is optional.",
"Be yourself; everyone else is already taken.",
"In three words, I can sum up everything I've learned about life: It goes on.",
"You can't stop the waves, but you can learn to surf.",
"We accept the love we think we deserve.",
"It’s never too late to be what you might have been.",
"Every moment is a fresh beginning.",
"The best way out is always through.",
"There is no friend as loyal as a book.",
"You are never too old to set another goal or to dream a new dream.",
"Life isn’t about finding yourself. Life is about creating yourself."

]